from app.models import Question, QuestionSet

WATER_CYCLE_QUESTION_SET = QuestionSet(
    questions=[
        Question(
            concept="Evaporation",
            question_text="Where does most of the water that evaporates into the atmosphere come from?",
            options=["Oceans", "Puddles", "Underground aquifers", "Melting glaciers"],
            correct_answers=[1],
            is_select_all=False,
            explanation="Oceans hold the vast majority of Earth's water, so they supply most evaporated water.",
            page_number=1,
            source_quote="The ocean, covering most of Earth's surface, is the single largest source of evaporated water.",
        ),
        Question(
            concept="Evaporation",
            question_text="Which of these are ways water enters the atmosphere as vapor? (Select all that apply)",
            options=["Evaporation from open water", "Transpiration from plants", "Sublimation from ice and snow", "Infiltration into soil"],
            correct_answers=[1, 2, 3],
            is_select_all=True,
            explanation="Water enters the atmosphere via evaporation, transpiration, and sublimation. Infiltration moves water into soil, not into the air.",
            page_number=1,
            source_quote="Water vapor enters the atmosphere through evaporation, transpiration, and sublimation.",
        ),
        Question(
            concept="Transpiration",
            question_text="What is transpiration?",
            options=["Water vapor released from plant leaves", "Rain falling through a forest canopy", "Water pooling on leaf surfaces", "Roots absorbing groundwater"],
            correct_answers=[1],
            is_select_all=False,
            explanation="Transpiration is the release of water vapor from plant leaves into the atmosphere.",
            page_number=1,
            source_quote="Plants release water vapor from their leaves in a process called transpiration.",
        ),
        Question(
            concept="Condensation",
            question_text="What atmospheric change causes water vapor to condense into cloud droplets?",
            options=["Rising air cools below its dew point", "Air pressure at sea level increases", "Sunlight heats the vapor further", "Wind speed decreases near the ground"],
            correct_answers=[1],
            is_select_all=False,
            explanation="As moist air rises it cools; once it drops below the dew point, vapor condenses into tiny droplets that form clouds.",
            page_number=2,
            source_quote="As air rises and cools below its dew point, water vapor condenses into the tiny droplets that make up clouds.",
        ),
        Question(
            concept="Precipitation",
            question_text="Which of these are forms precipitation can take? (Select all that apply)",
            options=["Rain", "Snow", "Hail", "Fog"],
            correct_answers=[1, 2, 3],
            is_select_all=True,
            explanation="Rain, snow, and hail are all forms of precipitation. Fog is condensation near ground level, not precipitation.",
            page_number=2,
            source_quote="Precipitation reaches the ground as rain, snow, sleet, or hail, depending on temperature.",
        ),
        Question(
            concept="Runoff",
            question_text="What is surface runoff?",
            options=["Water flowing over land into streams and rivers", "Water seeping directly into an aquifer", "Water vapor cooling into clouds", "Water absorbed by plant roots"],
            correct_answers=[1],
            is_select_all=False,
            explanation="Surface runoff is water flowing over the land surface into streams, rivers, and eventually larger bodies of water.",
            page_number=3,
            source_quote="Runoff is water that flows across the land surface into streams and rivers rather than soaking into the ground.",
        ),
        Question(
            concept="Groundwater",
            question_text="Groundwater is stored underground in formations called what?",
            options=["Aquifers", "Deltas", "Watersheds", "Reservoirs"],
            correct_answers=[1],
            is_select_all=False,
            explanation="Aquifers are underground rock and soil formations that store groundwater, sometimes for thousands of years.",
            page_number=3,
            source_quote="Groundwater accumulates in underground formations known as aquifers.",
        ),
        Question(
            concept="Water cycle overview",
            question_text="Which of these processes are part of the water cycle? (Select all that apply)",
            options=["Evaporation", "Condensation", "Precipitation", "Photosynthesis"],
            correct_answers=[1, 2, 3],
            is_select_all=True,
            explanation="Evaporation, condensation, and precipitation are core water cycle stages. Photosynthesis is a separate biological process.",
            page_number=1,
            source_quote="The water cycle consists of evaporation, condensation, and precipitation, repeating continuously.",
        ),
    ]
)
